### ISSUE TITLE
RB Digital/ Zinio / Readly

### ISSUE THREAD

**Issue by JackJones2018** [PrawnCocktail/ReadlyFetcher#2]
Hi, this works well for readly but do you know if this would work for zinio or rbdigital subscriptions? When browsing the websites they seem to look the same with same layout etc?

Thanks

**Comment by PrawnCocktail** [comment]
Sorry, I missed this completely. 
I don't think this would work with either of the sites in its current form, however after checking out the two sites you mention, i think zinio is probably do-able with some work, but i couldn't find a way to subscribe monthly to that site, it all seems to be individual magazine prices, at least where i am in the world. 
rbdigital is just showing audio related stuff, so i don't think that would be possible. 

If i make a tool for zinio, i will try to remember to reply to this, but as of right now, I'm going to lock this. 
Thanks
